import Head from 'next/head'
import { useAuth } from '../hooks/useAuth';
import { useRouter } from 'next/router';

export default function Dashboard() {

    const auth = useAuth();
    const router = useRouter();
    const handleSignout = async () => {
        if (await auth.signout()) {
            router.push('/login');
        } else {
            console.log("error signing out");
        }
    }

    function handleSearch() {
        router.push('/searchUser');
    }

    function handleEvents() {
        router.push('/eventPage');
    }
    function handleBatchEdit() {
        router.push('/batchEdit');
    }

    function handleExport() {
        router.push('/export');
    }

    // TODO: Break down into components
    return (

        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
                <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet"></link>
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center p-24">
                <h1 class="text-5xl font-bold">Dashboard</h1>
                <p class="py-3">What would you like to do?</p>
                <div class="flex flex-col space-y-3">
                    <button
                        class="btn btn-neutral"
                        onClick={() => handleEvents()}
                    >View events</button>
                    <button
                        class="btn btn-neutral"
                        onClick={() => handleSearch()}
                    >Search for a user</button>
                    <button
                        class="btn btn-neutral"
                        onClick={() => handleBatchEdit()}
                    >Batch edit users</button>
                    <button
                        class="btn btn-error"
                        onClick={() => handleSignout()}
                    >Log out</button>
                </div>
            </main>
        </div>
    )

}
