import Head from 'next/head'
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../hooks/useAuth';
import { signInWithPhoneNumber, RecaptchaVerifier, onSignInSubmit } from "firebase/auth";

export default function Login() {
    const [email, setEmail] = useState("")
    const [incorrectEmail, setIncorrectEmail] = useState(false);
    const [password, setPassword] = useState("");
    const [loading, setLoading] = useState(false)
    const auth = useAuth()
    const router = useRouter()


    const handleInput = async () => {
        setLoading(true);
        if (await auth.signInWithEmail(email, password)) {
            router.push('/dashboard');
        } else {
            setIncorrectEmail(true);
            setLoading(false);
        }
    }

    // TODO: Break down into components
    return (

        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
                <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet"></link>
            </Head>
            <main className='flex min-h-screen flex-col justify-center items-center space-y-3 p-24'>
                            <h1 className="text-5xl font-bold">Secretary Portal</h1>
                            {incorrectEmail === true ? <h2 className='text-md font-bold font-lato text-center text-red-500'>Incorrect username or password.</h2> : <p>Please enter your username and password to login.</p>}
                            <input
                                type="email"
                                value={email}
                                className="input input-bordered input-primary w-full max-w-xs"
                                placeholder='username'
                                onChange={e => setEmail(e.target.value)}
                            />
                            <input
                                type="password"
                                value={password}
                                placeholder='password'
                                className="input input-bordered input-primary w-full max-w-xs"
                                onChange={e => setPassword(e.target.value)}
                            />
                            {loading === true ? <div class="loading loading-lg"></div> :
                                <div>
                                    <button
                                        className="btn btn-primary"
                                        onClick={(e) => handleInput()}>Submit</button>
                                </div>
                            }
            </main>
        </div>
    )

}
