import Head from 'next/head'
import { useAuth } from '../hooks/useAuth';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function SearchUser() {

    const auth = useAuth();
    const router = useRouter();
    const [input, setInput] = useState();

    function handleSearch() {
        console.log(input);
    }


    // TODO: Break down into components
    return (

        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin></link>
                <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet"></link>
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center p-24">
                <h1 class="text-5xl font-bold">Search For a User</h1>
                <p class="py-3">Look up a user by name or phone number.</p>
                <div class="flex flex-col space-y-3">
                    <input type="text" placeholder="Enter name or number" className="input input-bordered w-full max-w-xs" value={input} onChange={() => setInput(e.target.value)}/>
                    <button
                        class="btn btn-neutral"
                        onClick={() => handleSearch()}
                    >Search</button>
                    <button
                        class="btn btn-neutral"
                        onClick={() => router.push('/dashboard')}
                    >Back</button>
                </div>
            </main>
        </div>
    )

}
